package com.smart.model;

// default package
// Generated 2017-7-5 11:01:11 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * ProjectInfoTransferRecord generated by hbm2java
 */
@Entity
@Table(name = "project_transfer_record", catalog = "eccs")
public class ProjectTransferRecord implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer cid;
	private ProjectInfo projectInfo;
	private String consultType;
	private String serviceContent;
	private Double bidPrice;
	private String currentStatus;
	private String noticeUrl;
	private String callBidFile;
	private String bidFile;
	private String ownerCompany;
	private String ownerName;
	private String ownerPosition;
	private String ownerTel;
	private String ownerAddr;
	private String event;
	private String eventTime;
	private String eventAddr;
	private String others;
	private Integer transferNo;
	private String transferPerson;
	private String receiver;
	private Integer status;
	private String createTime;
	private String transferTime;
	private String remark;
	
	//非数据库字段
	private boolean resStates; // 编辑操作权限

	public ProjectTransferRecord() {
	}

	public ProjectTransferRecord(Integer cid) {
		this.cid = cid;
	}

	public ProjectTransferRecord(Integer cid, ProjectInfo projectInfo, String consultType,
			String serviceContent, Double bidPrice, String currentStatus,
			String noticeUrl, String callBidFile, String bidFile,Integer transferNo,
			String ownerCompany, String ownerName, String ownerPosition,String transferTime,
			String ownerTel, String ownerAddr, String event, String eventTime,
			String eventAddr, String others, String transferPerson,
			String receiver, Integer status, String createTime, String remark) {
		this.cid = cid;
		this.projectInfo = projectInfo;
		this.consultType = consultType;
		this.serviceContent = serviceContent;
		this.bidPrice = bidPrice;
		this.currentStatus = currentStatus;
		this.noticeUrl = noticeUrl;
		this.transferNo = transferNo;
		this.callBidFile = callBidFile;
		this.bidFile = bidFile;
		this.ownerCompany = ownerCompany;
		this.ownerName = ownerName;
		this.ownerPosition = ownerPosition;
		this.ownerTel = ownerTel;
		this.ownerAddr = ownerAddr;
		this.event = event;
		this.eventTime = eventTime;
		this.eventAddr = eventAddr;
		this.others = others;
		this.transferPerson = transferPerson;
		this.receiver = receiver;
		this.status = status;
		this.createTime = createTime;
		this.transferTime = transferTime;
		this.remark = remark;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectInfo_id")
	@NotFound(action = NotFoundAction.IGNORE)
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}


	@Column(name = "consult_type", length = 32)
	public String getConsultType() {
		return this.consultType;
	}

	public void setConsultType(String consultType) {
		this.consultType = consultType;
	}

	@Column(name = "service_content", length = 64)
	public String getServiceContent() {
		return this.serviceContent;
	}

	public void setServiceContent(String serviceContent) {
		this.serviceContent = serviceContent;
	}

	@Column(name = "bid_price", precision = 22, scale = 0)
	public Double getBidPrice() {
		return this.bidPrice;
	}

	public void setBidPrice(Double bidPrice) {
		this.bidPrice = bidPrice;
	}

	@Column(name = "current_status", length = 64)
	public String getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(String currentStatus) {
		this.currentStatus = currentStatus;
	}

	@Column(name = "notice_url", length = 128)
	public String getNoticeUrl() {
		return this.noticeUrl;
	}

	public void setNoticeUrl(String noticeUrl) {
		this.noticeUrl = noticeUrl;
	}

	@Column(name = "call_bid_file", length = 128)
	public String getCallBidFile() {
		return this.callBidFile;
	}

	public void setCallBidFile(String callBidFile) {
		this.callBidFile = callBidFile;
	}

	@Column(name = "bid_file", length = 128)
	public String getBidFile() {
		return this.bidFile;
	}

	public void setBidFile(String bidFile) {
		this.bidFile = bidFile;
	}

	@Column(name = "owner_company", length = 64)
	public String getOwnerCompany() {
		return this.ownerCompany;
	}

	public void setOwnerCompany(String ownerCompany) {
		this.ownerCompany = ownerCompany;
	}

	@Column(name = "owner_name", length = 32)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "owner_position", length = 32)
	public String getOwnerPosition() {
		return this.ownerPosition;
	}

	public void setOwnerPosition(String ownerPosition) {
		this.ownerPosition = ownerPosition;
	}

	@Column(name = "owner_tel", length = 16)
	public String getOwnerTel() {
		return this.ownerTel;
	}

	public void setOwnerTel(String ownerTel) {
		this.ownerTel = ownerTel;
	}

	@Column(name = "owner_addr", length = 128)
	public String getOwnerAddr() {
		return this.ownerAddr;
	}

	public void setOwnerAddr(String ownerAddr) {
		this.ownerAddr = ownerAddr;
	}

	@Column(name = "event", length = 32)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "event_time", length = 19)
	public String getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(String eventTime) {
		this.eventTime = eventTime;
	}

	@Column(name = "event_addr", length = 19)
	public String getEventAddr() {
		return this.eventAddr;
	}

	public void setEventAddr(String eventAddr) {
		this.eventAddr = eventAddr;
	}

	@Column(name = "others", length = 128)
	public String getOthers() {
		return this.others;
	}

	public void setOthers(String others) {
		this.others = others;
	}

	@Column(name = "transfer_person", length = 64)
	public String getTransferPerson() {
		return this.transferPerson;
	}

	public void setTransferPerson(String transferPerson) {
		this.transferPerson = transferPerson;
	}

	@Column(name = "receiver", length = 32)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "create_time", length = 19)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "transfer_time", length = 19)
	public String getTransferTime() {
		return transferTime;
	}

	public void setTransferTime(String transferTime) {
		this.transferTime = transferTime;
	}

	@Column(name = "remark", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "transfer_no")
	public Integer getTransferNo() {
		return transferNo;
	}

	public void setTransferNo(Integer transferNo) {
		this.transferNo = transferNo;
	}

	@Transient
	public boolean getResStates() {
		return resStates;
	}

	public void setResStates(boolean resStates) {
		this.resStates = resStates;
	}

}
