package com.yhcrt.iHealthCloud.mapper;

import com.yhcrt.iHealthCloud.entity.HdTemperature;
import com.yhcrt.iHealthCloud.entity.HdTemperatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HdTemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    long countByExample(HdTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int deleteByExample(HdTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int insert(HdTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int insertSelective(HdTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    List<HdTemperature> selectByExample(HdTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    HdTemperature selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") HdTemperature record, @Param("example") HdTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByExample(@Param("record") HdTemperature record, @Param("example") HdTemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByPrimaryKeySelective(HdTemperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_temperature
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByPrimaryKey(HdTemperature record);
}