package com.smart.model;

// default package
// Generated 2017-7-5 11:01:11 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * BidApplyAssess generated by hbm2java
 */
@Entity
@Table(name = "bid_apply_assess", catalog = "eccs")
public class BidApplyAssess implements java.io.Serializable {

	private static final long serialVersionUID = -2701993089679788498L;
	private Integer cid;
	private ProjectInfo projectInfo;
	private String bidPkg;
	private T_Customer customer;
	private String consultType;
	private String callBidFile;
	private String agentCompany;
	private String applyDate;
	private String bidOpenDate;
	private String consultFee;
	private String signupCity;
	private Integer assessResult;
	private String appraisalnotes;
	private Integer completeStatus;
	private String getFileDate;
	private String createTime;
	private Integer status;
	private String remark;

	// 非数据库字段
	private boolean resStates; // 编辑操作权限
	// 非数据库字段
	private boolean checkStates; // 审核操作权限

	public BidApplyAssess() {
	}

	public BidApplyAssess(Integer cid) {
		this.cid = cid;
	}

	public BidApplyAssess(Integer cid, ProjectInfo projectInfo, String bidPkg,
			T_Customer customer, String consultType, String callBidFile,
			String agentCompany, String applyDate, String bidOpenDate,
			String consultFee, String signupCity, Integer assessResult,
			String appraisalnotes, Integer completeStatus, String getFileDate,
			String createTime, Integer status, String remark) {
		this.cid = cid;
		this.projectInfo = projectInfo;
		this.bidPkg = bidPkg;
		this.customer = customer;
		this.consultType = consultType;
		this.callBidFile = callBidFile;
		this.agentCompany = agentCompany;
		this.applyDate = applyDate;
		this.bidOpenDate = bidOpenDate;
		this.consultFee = consultFee;
		this.signupCity = signupCity;
		this.assessResult = assessResult;
		this.appraisalnotes = appraisalnotes;
		this.completeStatus = completeStatus;
		this.getFileDate = getFileDate;
		this.createTime = createTime;
		this.status = status;
		this.remark = remark;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectInfo_id")
	@NotFound(action = NotFoundAction.IGNORE)
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@Column(name = "bid_pkg", length = 64)
	public String getBidPkg() {
		return this.bidPkg;
	}

	public void setBidPkg(String bidPkg) {
		this.bidPkg = bidPkg;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	@NotFound(action = NotFoundAction.IGNORE)
	public T_Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(T_Customer customer) {
		this.customer = customer;
	}

	@Column(name = "consult_type", length = 32)
	public String getConsultType() {
		return this.consultType;
	}

	public void setConsultType(String consultType) {
		this.consultType = consultType;
	}

	@Column(name = "call_bid_file", length = 128)
	public String getCallBidFile() {
		return this.callBidFile;
	}

	public void setCallBidFile(String callBidFile) {
		this.callBidFile = callBidFile;
	}

	@Column(name = "agent_company", length = 64)
	public String getAgentCompany() {
		return this.agentCompany;
	}

	public void setAgentCompany(String agentCompany) {
		this.agentCompany = agentCompany;
	}

	@Column(name = "apply_date", length = 19)
	public String getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(String applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "bid_open_date", length = 19)
	public String getBidOpenDate() {
		return this.bidOpenDate;
	}

	public void setBidOpenDate(String bidOpenDate) {
		this.bidOpenDate = bidOpenDate;
	}

	@Column(name = "consult_fee", precision = 22, scale = 0)
	public String getConsultFee() {
		return this.consultFee;
	}

	public void setConsultFee(String consultFee) {
		this.consultFee = consultFee;
	}

	@Column(name = "signup_city", length = 32)
	public String getSignupCity() {
		return this.signupCity;
	}

	public void setSignupCity(String signupCity) {
		this.signupCity = signupCity;
	}

	@Column(name = "assess_result")
	public Integer getAssessResult() {
		return this.assessResult;
	}

	public void setAssessResult(Integer assessResult) {
		this.assessResult = assessResult;
	}

	@Column(name = "appraisalnotes", length = 128)
	public String getAppraisalnotes() {
		return this.appraisalnotes;
	}

	public void setAppraisalnotes(String appraisalnotes) {
		this.appraisalnotes = appraisalnotes;
	}

	@Column(name = "complete_status")
	public Integer getCompleteStatus() {
		return this.completeStatus;
	}

	public void setCompleteStatus(Integer completeStatus) {
		this.completeStatus = completeStatus;
	}

	@Column(name = "get_file_date", length = 19)
	public String getGetFileDate() {
		return this.getFileDate;
	}

	public void setGetFileDate(String getFileDate) {
		this.getFileDate = getFileDate;
	}

	@Column(name = "create_time", length = 19)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Transient
	public boolean getResStates() {
		return resStates;
	}

	public void setResStates(boolean resStates) {
		this.resStates = resStates;
	}

	@Transient
	public boolean getCheckStates() {
		return checkStates;
	}

	public void setCheckStates(boolean checkStates) {
		this.checkStates = checkStates;
	}

}
