package com.smart.model;

// default package
// Generated 2017-7-5 11:01:11 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * BidInfoQuote generated by hbm2java
 */
@Entity
@Table(name = "bid_info_quote", catalog = "eccs")
public class BidInfoQuote implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer cid;
	private ProjectInfo projectInfo;
	private String company;
	private Double quotedPrice;
	private Double budgetaryPrice;
	private Double ratio;

	public BidInfoQuote() {
	}

	public BidInfoQuote(Integer cid) {
		this.cid = cid;
	}

	public BidInfoQuote(Integer cid, ProjectInfo projectInfo, String company,
			Double quotedPrice, Double budgetaryPrice, Double ratio) {
		this.cid = cid;
		this.projectInfo = projectInfo;
		this.company = company;
		this.quotedPrice = quotedPrice;
		this.budgetaryPrice = budgetaryPrice;
		this.ratio = ratio;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectInfo_id")
	@NotFound(action = NotFoundAction.IGNORE)
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@Column(name = "company", length = 32)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "quoted_price", precision = 22, scale = 0)
	public Double getQuotedPrice() {
		return this.quotedPrice;
	}

	public void setQuotedPrice(Double quotedPrice) {
		this.quotedPrice = quotedPrice;
	}

	@Column(name = "budgetary_price", precision = 22, scale = 0)
	public Double getBudgetaryPrice() {
		return this.budgetaryPrice;
	}

	public void setBudgetaryPrice(Double budgetaryPrice) {
		this.budgetaryPrice = budgetaryPrice;
	}

	@Column(name = "ratio", precision = 22, scale = 0)
	public Double getRatio() {
		return this.ratio;
	}

	public void setRatio(Double ratio) {
		this.ratio = ratio;
	}

}
