package com.yhcrt.iHealthCloud.mapper;

import com.yhcrt.iHealthCloud.entity.HdBloodOxygen;
import com.yhcrt.iHealthCloud.entity.HdBloodOxygenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HdBloodOxygenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    long countByExample(HdBloodOxygenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int deleteByExample(HdBloodOxygenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int insert(HdBloodOxygen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int insertSelective(HdBloodOxygen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    List<HdBloodOxygen> selectByExample(HdBloodOxygenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    HdBloodOxygen selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") HdBloodOxygen record, @Param("example") HdBloodOxygenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByExample(@Param("record") HdBloodOxygen record, @Param("example") HdBloodOxygenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByPrimaryKeySelective(HdBloodOxygen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_blood_oxygen
     *
     * @mbg.generated Fri Jan 19 15:44:55 CST 2018
     */
    int updateByPrimaryKey(HdBloodOxygen record);
}