package com.smart.model;

// default package
// Generated 2017-7-5 11:01:11 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * BidBondAssess generated by hbm2java
 */
@Entity
@Table(name = "bid_bond_assess", catalog = "eccs")
public class BidBondAssess implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer cid;
	private Integer applyNo;
	private ProjectInfo projectInfo;
	private String bidPkg;
	private String remittancesName;
	private String remittancesAccount;
	private String depositBank;
	private String bankAccount;
	private Double remittanceAmount;
	private String deadline;
	private T_Customer customer;
	private String bidderTel;
	private String bidAgent;
	private String agentTel;
	private String specialRequirements;
	private String rreturnTime;
	private String returmSpecialInstr;
	private String auditOpinion;
	private Integer financeHandleSituation;
	private String createTime;
	private Integer status;
	private String remark;

	//非数据库字段
	private boolean resStates; // 编辑操作权限
	//非数据库字段
	private boolean checkStates; // 审核操作权限
	
	public BidBondAssess() {
	}

	public BidBondAssess(Integer cid) {
		this.cid = cid;
	}

	public BidBondAssess(Integer cid, Integer applyNo, ProjectInfo projectInfo,
			String bidPkg, String remittancesName, String remittancesAccount,
			String depositBank, String bankAccount, Double remittanceAmount,
			String deadline, T_Customer customer, String bidderTel, String bidAgent,
			String agentTel, String specialRequirements, String rreturnTime,
			String returmSpecialInstr, String auditOpinion,
			Integer financeHandleSituation, String createTime, Integer status,
			String remark) {
		this.cid = cid;
		this.applyNo = applyNo;
		this.projectInfo = projectInfo;
		this.bidPkg = bidPkg;
		this.remittancesName = remittancesName;
		this.remittancesAccount = remittancesAccount;
		this.depositBank = depositBank;
		this.bankAccount = bankAccount;
		this.remittanceAmount = remittanceAmount;
		this.deadline = deadline;
		this.customer = customer;
		this.bidderTel = bidderTel;
		this.bidAgent = bidAgent;
		this.agentTel = agentTel;
		this.specialRequirements = specialRequirements;
		this.rreturnTime = rreturnTime;
		this.returmSpecialInstr = returmSpecialInstr;
		this.auditOpinion = auditOpinion;
		this.financeHandleSituation = financeHandleSituation;
		this.createTime = createTime;
		this.status = status;
		this.remark = remark;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "apply_no")
	public Integer getApplyNo() {
		return this.applyNo;
	}

	public void setApplyNo(Integer applyNo) {
		this.applyNo = applyNo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectInfo_id")
	@NotFound(action = NotFoundAction.IGNORE)
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@Column(name = "bid_pkg", length = 32)
	public String getBidPkg() {
		return this.bidPkg;
	}

	public void setBidPkg(String bidPkg) {
		this.bidPkg = bidPkg;
	}

	@Column(name = "remittances_name", length = 32)
	public String getRemittancesName() {
		return this.remittancesName;
	}

	public void setRemittancesName(String remittancesName) {
		this.remittancesName = remittancesName;
	}

	@Column(name = "remittances_account", length = 32)
	public String getRemittancesAccount() {
		return this.remittancesAccount;
	}

	public void setRemittancesAccount(String remittancesAccount) {
		this.remittancesAccount = remittancesAccount;
	}

	@Column(name = "deposit_bank", length = 32)
	public String getDepositBank() {
		return this.depositBank;
	}

	public void setDepositBank(String depositBank) {
		this.depositBank = depositBank;
	}

	@Column(name = "bank_account", length = 32)
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	@Column(name = "remittance_amount", precision = 22, scale = 0)
	public Double getRemittanceAmount() {
		return this.remittanceAmount;
	}

	public void setRemittanceAmount(Double remittanceAmount) {
		this.remittanceAmount = remittanceAmount;
	}

	@Column(name = "deadline", length = 19)
	public String getDeadline() {
		return this.deadline;
	}

	public void setDeadline(String deadline) {
		this.deadline = deadline;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	@NotFound(action = NotFoundAction.IGNORE)
	public T_Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(T_Customer customer) {
		this.customer = customer;
	}

	@Column(name = "bidder_tel", length = 16)
	public String getBidderTel() {
		return this.bidderTel;
	}

	public void setBidderTel(String bidderTel) {
		this.bidderTel = bidderTel;
	}

	@Column(name = "bid_agent", length = 32)
	public String getBidAgent() {
		return this.bidAgent;
	}

	public void setBidAgent(String bidAgent) {
		this.bidAgent = bidAgent;
	}

	@Column(name = "agent_tel", length = 16)
	public String getAgentTel() {
		return this.agentTel;
	}

	public void setAgentTel(String agentTel) {
		this.agentTel = agentTel;
	}

	@Column(name = "special_requirements", length = 64)
	public String getSpecialRequirements() {
		return this.specialRequirements;
	}

	public void setSpecialRequirements(String specialRequirements) {
		this.specialRequirements = specialRequirements;
	}

	@Column(name = "rreturn_time", length = 19)
	public String getRreturnTime() {
		return this.rreturnTime;
	}

	public void setRreturnTime(String rreturnTime) {
		this.rreturnTime = rreturnTime;
	}

	@Column(name = "returm_special_instr", length = 128)
	public String getReturmSpecialInstr() {
		return this.returmSpecialInstr;
	}

	public void setReturmSpecialInstr(String returmSpecialInstr) {
		this.returmSpecialInstr = returmSpecialInstr;
	}

	@Column(name = "audit_opinion", length = 128)
	public String getAuditOpinion() {
		return this.auditOpinion;
	}

	public void setAuditOpinion(String auditOpinion) {
		this.auditOpinion = auditOpinion;
	}

	@Column(name = "finance_handle_situation")
	public Integer getFinanceHandleSituation() {
		return this.financeHandleSituation;
	}

	public void setFinanceHandleSituation(Integer financeHandleSituation) {
		this.financeHandleSituation = financeHandleSituation;
	}

	@Column(name = "create_time", length = 19)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Transient
	public boolean getResStates() {
		return resStates;
	}

	@Transient
	public boolean getCheckStates() {
		return checkStates;
	}

	public void setResStates(boolean resStates) {
		this.resStates = resStates;
	}

	public void setCheckStates(boolean checkStates) {
		this.checkStates = checkStates;
	}

}
